#!highlight yaml

heat_template_version: 2013-05-23

parameters:

  provider_pt_name:
    type: string
    label: Provider PT name
    description: Provider PT name

  consumer_pt_name:
    type: string
    label: Consumer PT name
    description: Consumer PT name

  provider_ptg:
    type: string
    label: Provider PTG id
    description: Provider PTG id

  consumer_ptg:
    type: string
    label: Consumer PTG id
    description: Consumer PTG id

resources:

# Create PTs in uset and app PTGs

    provider_pt:
        type: OS::Neutron::PolicyTarget
        properties:
            name: { get_param: provider_pt_name }
            policy_target_group_id: { get_param: provider_ptg }

    consumer_pt:
        type: OS::Neutron::PolicyTarget
        properties:
            name: { get_param: consumer_pt_name }
            policy_target_group_id: { get_param: provider_ptg }

# Setup resources for management network connectivity

    mgmt_l3_policy:
        type: OS::Neutron::L3Policy
        properties:
            name: Mgmt_IDS_L3_Policy
            ip_pool: '172.2.0.0/24'
            shared: False

    mgmt_l2_policy:
        type: OS::Neutron::L2Policy
        depends_on: mgmt_l3_policy
        properties:
            name: Management_IDS_Domain
            l3_policy_id: { get_resource: mgmt_l3_policy }
            shared: False

    mgmt_ptg:
        type: OS::Neutron::PolicyTargetGroup
        depends_on: [ mgmt_l2_policy ]
        properties:
            name: Mgmt_IDS_PTG
            l2_policy_id: { get_resource: mgmt_l2_policy }
            shared: False

    mgmt_pt:
        type: OS::Neutron::PolicyTarget
        properties:
            name: Mgmt_IDS_PT
            policy_target_group_id: { get_resource: mgmt_ptg }

# Launch IDS appliance

    ids_appliance:
        type: OS::Nova::Server
        properties:
            name: ids_appliance
            image: cirros-0.3.2-x86_64-uec
            flavor: m1.nano
            networks:
                - port: {get_attr: [mgmt_pt, port_id]}
                - port: {get_attr: [consumer_pt, port_id]}
                - port: {get_attr: [provider_pt, port_id]}
